# This file is used for all profiles 
# except those allocated by other files 
# (for example prod or test)

spring:
  application:
    name: taco-cloud
  
  datasource:
    generate-unique-name: false
    name: tacocloud
    username: user
    password: user
  
  data:
    rest:
      base-path: /data-api

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  
  rabbitmq:
    host: localhost
    port: 5672
  

# Propertie in OrderProps
taco:
  orders:
    pageSize: 10

# Settings for logging
# Use this or logback.xml
# _______________
# logging:
#   level:
#     root: WARN
#     org:
#       springframework:
#         security: DEBUG

# Use fillers for mix
# ____________________
# greeting:
#   welcome: You are using ${spring.application.name}.

